update-checker: true


teleport:
  cooldown-seconds: 5
  countdown-sound: BLOCK_NOTE_BLOCK_HAT
  countdown-volume: 1.0
  countdown-pitch: 1.2
  success-sound: ENTITY_ENDERMAN_TELEPORT
afk-auto-teleport-worlds:
  - world
