name: MarisSpawn
version: '1.0'
main: vn.maris.spawn.MarisSpawnPlugin
api-version: '1.21'
folia-supported: true
commands:
  spawn:
    description: Open spawn GUI or teleport to a spawn.
    usage: /spawn [name]
  warp:
    description: Teleport to a warp.
    usage: /warp <destination>
  setspawn:
    description: Set a spawn location.
    usage: /setspawn <name>
    permission: marisspawn.admin
  setwarp:
    description: Set a warp location.
    usage: /setwarp <name>
    permission: marisspawn.admin
  delwarp:
    description: Delete a warp location.
    usage: /delwarp <name>
    permission: marisspawn.admin
  afk:
    description: Open afk GUI or teleport to an afk location.
    usage: /afk [name]
  setafk:
    description: Set an afk location.
    usage: /setafk <name>
    permission: marisspawn.admin
  marispawn:
    description: Admin command for MarisSpawn.
    usage: /marispawn reload
    permission: marisspawn.admin
permissions:
  marisspawn.admin:
    default: op
